#!/usr/bin/env tsx
/**
 * Census-driven LEGI Archive Ingestion for French Law MCP.
 *
 * Reads data/census.json (generated by census.ts) and parses ALL texts
 * from the extracted DILA LEGI open data corpus. Produces seed JSON
 * files in data/seed/ and updates census.json with ingestion results.
 *
 * This is the FULL CORPUS ingestion — not limited to a handful of codes.
 *
 * Issue #97 invariants:
 *   - the corpus is resolved at runtime (newest global + every incremental
 *     delta from the DILA index), NEVER a hardcoded archive;
 *   - the census and the extraction must carry the SAME source stamp;
 *   - article versions are selected by [DATE_DEBUT, DATE_FIN) validity,
 *     not by longest content;
 *   - seeds are stamped with the source identity and per-provision validity;
 *   - partial ingestion FAILS LOUD: every dropped target is enumerated and
 *     the process exits non-zero. Never present a partial corpus as complete.
 *
 * Data source: https://echanges.dila.gouv.fr/OPENDATA/LEGI/
 * Licence: Licence Ouverte v2.0
 *
 * Usage:
 *   npm run ingest:legi                        # Full census-driven ingestion
 *   npm run ingest:legi -- --archive /path.tgz # Use specific archive (no deltas, loud)
 *   npm run ingest:legi -- --extracted /path    # Use already-extracted directory (marker required)
 *   npm run ingest:legi -- --codes-only         # Only ingest codes (skip TNC)
 *   npm run ingest:legi -- --limit 10           # Limit number of texts to ingest
 *   npm run ingest:legi -- --allow-unstamped    # accept an unprovable corpus (loud)
 */

import * as fs from 'fs';
import * as path from 'path';
import { fileURLToPath } from 'url';
import { parseLegiXml, type ParsedArticle } from './lib/parser.js';
import { resolveCorpus, type ExtractIdentity } from './lib/legi-acquire.js';
import { selectArticles } from './lib/version-select.js';
import { resolveTextDir } from './lib/text-path.js';
import { classifyZeroProvisionText, type ZeroProvisionStats } from './lib/ingest-outcome.js';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const SEED_DIR = path.resolve(__dirname, '../data/seed');
const DATA_DIR = path.resolve(__dirname, '../data');
const CENSUS_PATH = path.join(DATA_DIR, 'census.json');

// ---------------------------------------------------------------------------
// Census types
// ---------------------------------------------------------------------------

interface CensusLaw {
  id: string;
  title: string;
  title_en: string | null;
  identifier: string;        // LEGITEXT or JORFTEXT ID
  url: string | null;
  status: string;
  category: string;
  classification: string;
  classification_reason: string;
  ingested: boolean;
  provision_count: number;
  ingestion_date: string | null;
}

interface CensusSourceArchive {
  base: string;
  base_stamp: string;
  deltas_applied: number;
  last_delta: string | null;
  source_stamp: string;
  acquired_at: string;
}

interface CensusFile {
  schema_version: string;
  jurisdiction: string;
  jurisdiction_name: string;
  portal: string;
  census_date: string;
  agent: string;
  source_archive?: CensusSourceArchive;
  summary: {
    total_laws: number;
    total_provisions: number;
    ingestable: number;
    ocr_needed: number;
    inaccessible: number;
    excluded: number;
  };
  laws: CensusLaw[];
}

// ---------------------------------------------------------------------------
// CLI
// ---------------------------------------------------------------------------

interface CliArgs {
  archive?: string;
  extracted?: string;
  codesOnly: boolean;
  limit?: number;
  allowUnstamped: boolean;
}

function parseArgs(): CliArgs {
  const args = process.argv.slice(2);
  let archive: string | undefined;
  let extracted: string | undefined;
  let codesOnly = false;
  let limit: number | undefined;
  let allowUnstamped = false;

  for (let i = 0; i < args.length; i++) {
    if (args[i] === '--archive' && args[i + 1]) { archive = args[i + 1]; i++; }
    else if (args[i] === '--extracted' && args[i + 1]) { extracted = args[i + 1]; i++; }
    else if (args[i] === '--codes-only') { codesOnly = true; }
    else if (args[i] === '--limit' && args[i + 1]) { limit = parseInt(args[i + 1], 10); i++; }
    else if (args[i] === '--allow-unstamped') { allowUnstamped = true; }
  }
  return { archive, extracted, codesOnly, limit, allowUnstamped };
}

// ---------------------------------------------------------------------------
// LEGI archive helpers
// ---------------------------------------------------------------------------

function walkXmlFiles(dir: string): string[] {
  const results: string[] = [];
  if (!fs.existsSync(dir)) return results;
  const walk = (d: string) => {
    let entries;
    try { entries = fs.readdirSync(d, { withFileTypes: true }); } catch { return; }
    for (const entry of entries) {
      const fp = path.join(d, entry.name);
      if (entry.isDirectory()) walk(fp);
      else if (entry.name.endsWith('.xml') && entry.name.startsWith('LEGIARTI')) results.push(fp);
    }
  };
  walk(dir);
  return results;
}

// ---------------------------------------------------------------------------
// Parse a single text from the extracted archive
// ---------------------------------------------------------------------------

interface ParsedProvision {
  provision_ref: string;
  chapter?: string;
  section: string;
  title: string;
  content: string;
  valid_from?: string;
  valid_to?: string;
}

interface ParsedLaw {
  documentId: string;
  title: string;
  titleEn: string | null;
  shortName: string | null;
  status: string;
  url: string | null;
  description: string | null;
  provisions: ParsedProvision[];
  /** Article-level evidence for zero-provision classification (issue #97). */
  stats: ZeroProvisionStats;
}

function parseTextDirectory(textDir: string, censusEntry: CensusLaw, today: string): ParsedLaw {
  const articleFiles = walkXmlFiles(textDir);

  const candidates: ParsedArticle[] = [];
  let fileErrors = 0;
  let parseErrors = 0;
  let articleNodesSeen = 0;

  for (const xmlFile of articleFiles) {
    try {
      const xmlContent = fs.readFileSync(xmlFile, 'utf-8');
      const result = parseLegiXml(xmlContent);
      articleNodesSeen += result.articleNodesSeen;
      parseErrors += result.errors.length;
      candidates.push(...result.articles);
    } catch {
      fileErrors++;
    }
  }

  // Validity-aware version selection per article number (issue #97: the old
  // keep-longest dedupe could serve an outdated longer version forever).
  const nonEmpty = candidates.filter((a) => a.content.trim().length > 0);
  const { selected, droppedExpiredNums } = selectArticles(nonEmpty, today);

  const provisions: ParsedProvision[] = selected.map((article) => ({
    provision_ref: `art${article.normalizedNum}`,
    section: article.normalizedNum,
    title: article.title,
    content: article.content,
    ...(article.dateDebut ? { valid_from: article.dateDebut } : {}),
    ...(article.dateFin ? { valid_to: article.dateFin } : {}),
  }));

  return {
    documentId: censusEntry.id,
    title: censusEntry.title,
    titleEn: censusEntry.title_en,
    shortName: null,
    status: censusEntry.status,
    url: censusEntry.url,
    description: null,
    provisions,
    stats: {
      articleFiles: articleFiles.length,
      fileErrors,
      parseErrors,
      articleNodesSeen,
      vigueurVersions: candidates.length,
      nonEmptyVigueurVersions: nonEmpty.length,
      expiredOnlyNums: droppedExpiredNums.length,
    },
  };
}

// ---------------------------------------------------------------------------
// Seed writers
// ---------------------------------------------------------------------------

function writeSeed(law: ParsedLaw, identity: ExtractIdentity, retrievedAt: string): void {
  fs.mkdirSync(SEED_DIR, { recursive: true });
  const seed = {
    id: law.documentId,
    type: 'statute',
    title: law.title,
    title_en: law.titleEn,
    short_name: law.shortName,
    status: law.status === 'repealed' ? 'repealed' : law.status === 'amended' ? 'amended' : 'in_force',
    url: law.url,
    description: law.description,
    provisions: law.provisions,
    _ingest: {
      retrieved_at: retrievedAt,
      source_base: identity.base,
      source_last_delta: identity.deltas_applied.at(-1) ?? null,
      source_stamp: identity.source_stamp,
    },
  };
  const fp = path.join(SEED_DIR, `${law.documentId}.json`);
  fs.writeFileSync(fp, JSON.stringify(seed, null, 2), 'utf-8');
}

function writeEuReferences(): void {
  const euData = {
    eu_documents: [
      { id: 'regulation:2016/679', type: 'regulation', year: 2016, number: 679, community: 'EU', celex_number: '32016R0679', title: 'General Data Protection Regulation (GDPR)', short_name: 'GDPR', url_eur_lex: 'https://eur-lex.europa.eu/eli/reg/2016/679/oj', in_force: true },
      { id: 'directive:2022/2555', type: 'directive', year: 2022, number: 2555, community: 'EU', celex_number: '32022L2555', title: 'NIS 2 Directive', short_name: 'NIS 2', url_eur_lex: 'https://eur-lex.europa.eu/eli/dir/2022/2555', in_force: true },
      { id: 'directive:2016/1148', type: 'directive', year: 2016, number: 1148, community: 'EU', celex_number: '32016L1148', title: 'NIS 1 Directive', short_name: 'NIS 1', url_eur_lex: 'https://eur-lex.europa.eu/eli/dir/2016/1148', in_force: false },
      { id: 'directive:2013/40', type: 'directive', year: 2013, number: 40, community: 'EU', celex_number: '32013L0040', title: 'Cybercrime Directive', short_name: 'Cybercrime Directive', url_eur_lex: 'https://eur-lex.europa.eu/eli/dir/2013/40', in_force: true },
      { id: 'regulation:2019/881', type: 'regulation', year: 2019, number: 881, community: 'EU', celex_number: '32019R0881', title: 'Cybersecurity Act', short_name: 'Cybersecurity Act', url_eur_lex: 'https://eur-lex.europa.eu/eli/reg/2019/881', in_force: true },
      { id: 'regulation:2024/1689', type: 'regulation', year: 2024, number: 1689, community: 'EU', celex_number: '32024R1689', title: 'EU AI Act', short_name: 'AI Act', url_eur_lex: 'https://eur-lex.europa.eu/eli/reg/2024/1689', in_force: true },
      { id: 'regulation:2022/2554', type: 'regulation', year: 2022, number: 2554, community: 'EU', celex_number: '32022R2554', title: 'Digital Operational Resilience Act (DORA)', short_name: 'DORA', url_eur_lex: 'https://eur-lex.europa.eu/eli/reg/2022/2554', in_force: true },
      { id: 'directive:2002/58', type: 'directive', year: 2002, number: 58, community: 'EU', celex_number: '32002L0058', title: 'ePrivacy Directive', short_name: 'ePrivacy Directive', url_eur_lex: 'https://eur-lex.europa.eu/eli/dir/2002/58', in_force: true },
    ],
    eu_references: [
      { source_type: 'document', source_id: 'code-penal', document_id: 'code-penal', eu_document_id: 'directive:2013/40', reference_type: 'implements', is_primary_implementation: true, implementation_status: 'complete', reference_context: 'Articles 323-1 to 323-7 implement the Cybercrime Directive requirements for criminalizing illegal access, system interference, and data interference.' },
      { source_type: 'document', source_id: 'loi-informatique-libertes', document_id: 'loi-informatique-libertes', eu_document_id: 'regulation:2016/679', reference_type: 'supplements', is_primary_implementation: true, implementation_status: 'complete', reference_context: 'The Loi Informatique et Libertes was extensively amended in 2018 to supplement the GDPR.' },
      { source_type: 'document', source_id: 'code-defense', document_id: 'code-defense', eu_document_id: 'directive:2016/1148', reference_type: 'implements', is_primary_implementation: true, implementation_status: 'complete', reference_context: 'The OIV framework (Articles L. 1332-1 et seq.) predates and exceeds NIS 1 requirements.' },
      { source_type: 'document', source_id: 'code-postes-telecom', document_id: 'code-postes-telecom', eu_document_id: 'directive:2002/58', reference_type: 'implements', is_primary_implementation: false, implementation_status: 'complete', reference_context: 'Telecommunications data retention and security provisions implement ePrivacy Directive requirements.' },
      { source_type: 'document', source_id: 'code-monetaire-et-financier', document_id: 'code-monetaire-et-financier', eu_document_id: 'regulation:2022/2554', reference_type: 'implements', is_primary_implementation: false, implementation_status: 'partial', reference_context: 'Financial sector provisions support DORA implementation for ICT risk management.' },
    ],
  };
  const fp = path.join(SEED_DIR, 'eu-references.json');
  fs.writeFileSync(fp, JSON.stringify(euData, null, 2), 'utf-8');
  console.log(`Wrote EU references: ${fp}`);
}

function writeManualSeeds(): void {
  const seeds = [
    {
      id: 'loi-programmation-militaire-cyber', type: 'statute',
      title: "Loi n° 2023-703 du 1er août 2023 relative à la programmation militaire 2024-2030",
      title_en: 'Military Programming Law 2024-2030 (cyber provisions)',
      short_name: 'LPM 2024-2030 (cyber)', status: 'in_force',
      issued_date: '2023-08-01', in_force_date: '2023-08-02',
      url: 'https://www.legifrance.gouv.fr/jorf/id/JORFTEXT000047914986',
      description: 'Expands ANSSI powers for cyber threat detection and response.',
      provisions: [
        { provision_ref: 'art64', chapter: 'Chapitre V', section: '64', title: 'Article 64 - ANSSI DNS threat blocking', content: "Lorsqu'il est constaté qu'une menace susceptible de porter atteinte à la sécurité nationale résulte de l'exploitation d'un nom de domaine, l'autorité nationale en matière de sécurité des systèmes d'information peut demander à toute personne concourant à l'adressage par noms de domaine sur internet de prendre les mesures les plus adaptées pour neutraliser cette menace." },
        { provision_ref: 'art65', chapter: 'Chapitre V', section: '65', title: 'Article 65 - Extended data collection for ANSSI', content: "Pour les besoins de la sécurité des systèmes d'information, l'autorité nationale en matière de sécurité des systèmes d'information peut mettre en oeuvre des dispositifs mettant en oeuvre des marqueurs techniques aux seules fins de détecter des événements susceptibles d'affecter la sécurité des systèmes d'information." },
        { provision_ref: 'art66', chapter: 'Chapitre V', section: '66', title: 'Article 66 - Vulnerability disclosure coordination', content: "L'autorité nationale en matière de sécurité des systèmes d'information peut imposer aux opérateurs de communications électroniques la mise en oeuvre de mesures de filtrage de noms de domaine utilisées par un attaquant." },
      ],
    },
    {
      id: 'nis2-transposition-france', type: 'statute',
      title: 'Cadre de transposition de la directive NIS 2 en droit français',
      title_en: 'Framework for NIS 2 Directive transposition into French law',
      short_name: 'NIS 2 FR transposition', status: 'not_yet_in_force',
      url: 'https://cyber.gouv.fr/la-directive-nis-2',
      description: "France's transposition of NIS 2 Directive.",
      provisions: [
        { provision_ref: 'art-scope', section: 'scope', title: 'Scope - Essential and Important Entities', content: "La transposition NIS 2 distingue les 'entités essentielles' (EE) et les 'entités importantes' (EI)." },
        { provision_ref: 'art-notification', section: 'notification', title: "Notification d'incidents", content: "Alerte précoce dans les 24h, notification complète dans les 72h, rapport final dans un mois." },
        { provision_ref: 'art-measures', section: 'measures', title: 'Mesures de gestion des risques', content: "Mesures techniques, opérationnelles et organisationnelles appropriées." },
        { provision_ref: 'art-sanctions', section: 'sanctions', title: 'Sanctions', content: "EE: jusqu'à 10M EUR ou 2% CA. EI: 7M EUR ou 1,4% CA." },
      ],
    },
  ];
  for (const seed of seeds) {
    const fp = path.join(SEED_DIR, `${seed.id}.json`);
    fs.writeFileSync(fp, JSON.stringify(seed, null, 2), 'utf-8');
    console.log(`Wrote manual seed: ${fp} (${seed.provisions.length} provisions)`);
  }
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

interface DroppedTarget {
  id: string;
  identifier: string;
  reason: string;
}

async function main(): Promise<void> {
  const { archive, extracted, codesOnly, limit, allowUnstamped } = parseArgs();

  console.log('=== French Law MCP — Census-Driven LEGI Ingestion ===\n');

  // Load census
  if (!fs.existsSync(CENSUS_PATH)) {
    console.error(`Census file not found: ${CENSUS_PATH}`);
    console.error('Run census first: npx tsx scripts/census.ts');
    process.exit(1);
  }

  const census: CensusFile = JSON.parse(fs.readFileSync(CENSUS_PATH, 'utf-8'));
  console.log(`Census loaded: ${census.laws.length} texts`);

  // Acquire the corpus and verify it is the SAME corpus the census saw.
  const { extractDir, identity } = await resolveCorpus({ archive, extracted, allowUnstamped });
  const today = new Date().toISOString().split('T')[0];

  if (!census.source_archive) {
    console.error(
      'Census carries no source_archive stamp — it predates source-identity stamping (issue #97) ' +
        'and its corpus version is unprovable. Re-run: npx tsx scripts/census.ts',
    );
    process.exit(1);
  }
  if (identity.source_stamp === 'unstamped' || census.source_archive.source_stamp === 'unstamped') {
    console.warn(
      'WARNING: unstamped corpus and/or census — census/extraction consistency CANNOT be verified.',
    );
  } else if (census.source_archive.source_stamp !== identity.source_stamp) {
    console.error(
      `Census was taken from source stamp ${census.source_archive.source_stamp} but the extraction ` +
        `is at ${identity.source_stamp}. Re-run census against the current corpus: npx tsx scripts/census.ts`,
    );
    process.exit(1);
  }

  // Filter to ingestable texts.
  // Default: codes + lois + ordonnances (primary legislation)
  // --codes-only: only codes
  let targets = census.laws.filter(l => l.classification === 'ingestable');
  if (codesOnly) {
    targets = targets.filter(l => l.category === 'code');
    console.log(`Codes-only mode: ${targets.length} codes`);
  } else {
    // Default: codes + lois + ordonnances (primary consolidated legislation)
    const PRIMARY_CATEGORIES = new Set(['code', 'loi', 'ordonnance']);
    targets = targets.filter(l => PRIMARY_CATEGORIES.has(l.category));
    console.log(`Primary legislation mode: ${targets.length} texts (codes + lois + ordonnances)`);
  }
  if (limit) {
    targets = targets.slice(0, limit);
    console.log(`Limited to ${limit} texts`);
  }

  console.log(`Texts to ingest: ${targets.length}\n`);

  // Clear old seed files (except eu-references.json)
  if (fs.existsSync(SEED_DIR)) {
    const oldFiles = fs.readdirSync(SEED_DIR).filter(f =>
      f.endsWith('.json') && f !== 'eu-references.json'
    );
    for (const f of oldFiles) {
      fs.unlinkSync(path.join(SEED_DIR, f));
    }
    console.log(`Cleared ${oldFiles.length} old seed files`);
  }
  fs.mkdirSync(SEED_DIR, { recursive: true });

  // Ingest each text
  const results: Array<{ id: string; provisions: number }> = [];
  const dropped: DroppedTarget[] = [];
  const outOfForce: DroppedTarget[] = [];
  let totalProvisions = 0;
  let processed = 0;
  let totalFileErrors = 0;
  let totalExpiredNums = 0;
  const retrievedAt = new Date().toISOString();

  for (const entry of targets) {
    processed++;

    // Resolve the text directory from the LEGITEXT/JORFTEXT identifier.
    // LEGITEXT-keyed texts live under code_en_vigueur OR TNC_en_vigueur
    // (consolidated lois/ordonnances) — the old single-prefix mapping
    // silently dropped the latter (73 texts in the 2026-06 corpus).
    const { dir: textDir, checked } = resolveTextDir(extractDir, entry.identifier);

    if (textDir === null) {
      dropped.push({
        id: entry.id,
        identifier: entry.identifier,
        reason: `directory not found in extracted corpus (checked: ${checked.join(', ')})`,
      });
      continue;
    }

    const law = parseTextDirectory(textDir, entry, today);
    totalFileErrors += law.stats.fileErrors;
    totalExpiredNums += law.stats.expiredOnlyNums;

    if (law.provisions.length === 0) {
      // Article-level evidence decides whether this is an EXPECTED exclusion
      // (text wholly out of force upstream) or a real ingestion anomaly. The
      // text-level TEXTE_VERSION status cannot be trusted for this (DILA keeps
      // VIGUEUR text metadata on abrogated texts).
      const outcome = classifyZeroProvisionText(law.stats);
      const target = { id: entry.id, identifier: entry.identifier, reason: outcome.reason };
      if (outcome.kind === 'out_of_force') {
        outOfForce.push(target);
      } else {
        dropped.push(target);
      }
      continue;
    }

    writeSeed(law, identity, retrievedAt);
    results.push({ id: law.documentId, provisions: law.provisions.length });
    totalProvisions += law.provisions.length;

    // Update census entry
    entry.ingested = true;
    entry.provision_count = law.provisions.length;
    entry.ingestion_date = today;

    if (processed % 50 === 0 || processed === targets.length) {
      console.log(`  [${processed}/${targets.length}] ${entry.id}: ${law.provisions.length} provisions (running total: ${totalProvisions})`);
    }
  }

  // Write EU references and manual seeds
  writeEuReferences();
  writeManualSeeds();

  // Update census with ingestion results
  census.summary.total_provisions = totalProvisions;
  fs.writeFileSync(CENSUS_PATH, JSON.stringify(census, null, 2), 'utf-8');
  console.log(`\nUpdated census: ${CENSUS_PATH}`);

  // Summary
  console.log('\n=== Ingestion Summary ===');
  console.log(`Source corpus: ${identity.base} + ${identity.deltas_applied.length} deltas (stamp ${identity.source_stamp})`);
  console.log(`Processed: ${processed} texts`);
  console.log(`Ingested: ${results.length} texts with provisions`);
  console.log(`Excluded as out of force: ${outOfForce.length}`);
  console.log(`Dropped (anomalies): ${dropped.length}`);
  console.log(`Total provisions: ${totalProvisions}`);
  console.log(`Article files unreadable/unparseable: ${totalFileErrors}`);
  console.log(`Article numbers excluded (no in-force version): ${totalExpiredNums}`);

  // Top 10 largest
  results.sort((a, b) => b.provisions - a.provisions);
  console.log('\nTop 10 largest:');
  for (const r of results.slice(0, 10)) {
    console.log(`  ${r.id}: ${r.provisions} provisions`);
  }

  console.log('\n+ 2 manual seeds (LPM 2024-2030 cyber, NIS 2 transposition)');

  // Expected exclusions: texts the article-level evidence proves wholly out
  // of force. Enumerated for auditability — these are NOT failures.
  if (outOfForce.length > 0) {
    console.log(`\n=== EXCLUDED OUT-OF-FORCE TEXTS (${outOfForce.length}) — expected, not failures ===`);
    for (const d of outOfForce) {
      console.log(`  ${d.id} (${d.identifier}): ${d.reason}`);
    }
  }

  // FAIL LOUD on partial ingestion (issue #97 / no-silent-fallbacks): every
  // anomalous target is enumerated and the exit code is non-zero. A non-zero
  // exit means DO NOT ship this seed set without investigating the drops.
  if (dropped.length > 0) {
    console.error(`\n=== DROPPED TARGETS (${dropped.length}) — PARTIAL INGESTION, exit 1 ===`);
    for (const d of dropped) {
      console.error(`  ${d.id} (${d.identifier}): ${d.reason}`);
    }
    console.error('\nSeeds for successful texts were written, but the corpus is INCOMPLETE.');
    process.exit(1);
  }

  console.log('\nNext step: npm run build:db');
}

main().catch(err => {
  console.error('LEGI ingestion failed:', err);
  process.exit(1);
});
